version: "3.4"

services:
  custom-prometheus-exporter-go:
    image: mrmyiagi/custom-prometheus-exporter-go
    container_name: custom-prometheus-exporter-go
    build:
      context: go
      dockerfile: Dockerfile
    ports:
      - "9010:8080"
    environment: 
    - URL=${URL}
    - CLIENTID=${CLIENTID}
    - CLIENTPASSWORD=${CLIENTPASSWORD} 
    restart: unless-stopped


  custom-prometheus-exporter-csharp:
    image: mrmyiagi/custom-prometheus-exporter-csharp
    container_name: custom-prometheus-exporter-csharp
    build:
      context: csharp
      dockerfile: Dockerfile
    ports:
      - "9011:8070"
    environment: 
    - URL=${URL}
    - CLIENTID=${CLIENTID}
    - CLIENTPASSWORD=${CLIENTPASSWORD} 
    restart: unless-stopped


  custom-prometheus-exporter-java:
    image: mrmyiagi/custom-prometheus-exporter-java
    container_name: custom-prometheus-exporter-java
    build:
      context: java
      dockerfile: Dockerfile
    ports:
      - "9012:8080"
    environment: 
    - URL=${URL}
    - CLIENTID=${CLIENTID}
    - CLIENTPASSWORD=${CLIENTPASSWORD} 
    restart: unless-stopped

  custom-prometheus-exporter-powershell:
    image: mrmyiagi/custom-prometheus-exporter-powershell
    container_name: custom-prometheus-exporter-powershell
    build:
      context: powershell
      dockerfile: Dockerfile
    ports:
      - "9013:8080"
    environment: 
    - URL=${URL}
    - CLIENTID=${CLIENTID}
    - CLIENTPASSWORD=${CLIENTPASSWORD}
    depends_on: 
      - prometheus-pushgateway 
    restart: unless-stopped

  prometheus-pushgateway:
    image: prom/pushgateway:latest 
    container_name: prometheus-pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped    

networks:
  default:
    external:
      name: custom-prometheus-exporter
